name: AdvancementNametag
version: '${project.version}'
main: me.xingyan.advancementnametag.AdvancementNametag
api-version: 1.20
author: xy
folia-supported: true
softdepend: [PlaceholderAPI]
commands:
  tags:
    description: open a gui to set the nametag
    usage: /<command>
